project_name: sitecrawl

before:
  hooks:
    - go mod tidy

builds:
  - id: sitecrawl
    main: ./cmd/sitecrawl
    binary: sitecrawl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - sitecrawl
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: sitecrawl
    directory: Formula
    homepage: "https://github.com/{{ .Env.HOMEBREW_TAP_OWNER }}/{{ .Env.HOMEBREW_TAP_NAME }}"
    description: "Chrome-powered website crawler with agent-ready report output"
    license: "MIT"
    repository:
      owner: "{{ .Env.HOMEBREW_TAP_OWNER }}"
      name: "{{ .Env.HOMEBREW_TAP_NAME }}"
      branch: "{{ .Env.HOMEBREW_TAP_BRANCH }}"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: sitecrawl-bot
      email: actions@github.com
    test: |
      system "#{bin}/sitecrawl", "--help"
    install: |
      bin.install "sitecrawl"

release:
  draft: false
  prerelease: auto
